spring:
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
datasource:
  connection:
    url: 'jdbc:postgresql://127.0.0.1:5432/rootDB'
  driver:
    class: org.postgresql.Driver
  security:
    username: root
    password: root